sudo: required
language: generic

services:
  - docker

env:
  global:
    - TRAVIS_DEBIAN_EXTRA_REPOSITORY="http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
    - TRAVIS_DEBIAN_LINTIAN=false
    - TRAVIS_DEBIAN_BACKPORTS=xenial-security
    - TRAVIS_DEBIAN_SECURITY_UPDATES=true
  matrix:
    - TRAVIS_DEBIAN_DERIVATIVE=ubuntu TRAVIS_DEBIAN_DISTRIBUTION=xenial


script:
  - wget -O- http://travis.debian.net/script.sh | sh -

