Document: capnproto
Title: Debian capnproto Manual
Author: <insert document author here>
Abstract: This manual describes what capnproto is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/capnproto/capnproto.sgml.gz

Format: postscript
Files: /usr/share/doc/capnproto/capnproto.ps.gz

Format: text
Files: /usr/share/doc/capnproto/capnproto.text.gz

Format: HTML
Index: /usr/share/doc/capnproto/html/index.html
Files: /usr/share/doc/capnproto/html/*.html
