#!/usr/bin/dh-exec

usr/lib/${DEB_HOST_MULTIARCH}/libcapnp.a
usr/lib/${DEB_HOST_MULTIARCH}/libcapnp.so
usr/lib/${DEB_HOST_MULTIARCH}/libcapnp-rpc.a
usr/lib/${DEB_HOST_MULTIARCH}/libcapnp-rpc.so
usr/lib/${DEB_HOST_MULTIARCH}/libcapnpc.a
usr/lib/${DEB_HOST_MULTIARCH}/libcapnpc.so
usr/lib/${DEB_HOST_MULTIARCH}/libkj.a
usr/lib/${DEB_HOST_MULTIARCH}/libkj.so
usr/lib/${DEB_HOST_MULTIARCH}/libkj-async.a
usr/lib/${DEB_HOST_MULTIARCH}/libkj-async.so
usr/lib/${DEB_HOST_MULTIARCH}/pkgconfig
usr/lib/${DEB_HOST_MULTIARCH}/cmake
usr/include
