on:
  push:
    branches:
      - debian/master
  pull_request: {}

jobs:
  sid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # FIXME massive hack, just trying to see if this works
      - name: prepare
        run: |
          set -ex
          git fetch --all
          git branch pristine-tar origin/pristine-tar
          git branch upstream/latest origin/upstream/latest
          sudo apt-get update
          sudo apt-get install -y git-buildpackage sbuild build-essential devscripts sudo
          export DEBARCH="$(dpkg --print-architecture)"
          cp /usr/share/doc/sbuild/examples/example.sbuildrc "$HOME/.sbuildrc"
          sudo sbuild-createchroot --include=eatmydata,ccache unstable /srv/chroot/unstable-${DEBARCH}-sbuild http://ftp.us.debian.org/debian
          sudo sbuild-adduser "$USER"
          cat >"$HOME/.gbp.conf" <<-EOF
          [DEFAULT]
          cleaner = git reset --hard HEAD && git clean -xdf
          builder = sbuild
          pristine-tar = True
          postbuild = lintian -I $GBP_CHANGES_FILE && echo "Lintian OK" && autopkgtest $GBP_CHANGES_FILE -- schroot unstable-${DEBARCH}-sbuild; [ $? -eq 0 -o $? -eq 8 ]
          [buildpackage]
          sign-tags = False
          upstream-tree = BRANCH
          ignore-branch = True
          [dch]
          spawn-editor = never
          EOF
      - name: build and test
        run: sudo gbp buildpackage

